[tool.djlint]
blank_line_after_tag = "endblock, load, extends"
blank_line_before_tag = "block"
close_void_tags = true
format_attribute_template_tags = true
format_js = true
max_line_length = 80
[tool.djlint.js]
indent_size = 2